name: Harris
favicon: null
layout_spectrum: 0.962059601675719
typography_spectrum: 0.8188248430378735
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17271d'
    - '#93ab6f'
    - '#8d7e85'
    - '#dddea3'
    - '#8dc6fb'
  brandStrength: 0
  lightness: 0.4865991303231567
  saturation: 0.3209846755489707
  rhythmicContrast: 0.4733521610032767
purpose: []
