name: Harris
favicon: null
layout_spectrum: 0.962059601675719
typography_spectrum: 0.8188248430378735
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5376807313878089
  lightness: 0.4865991303231567
  saturation: 0.3209846755489707
  rhythmicContrast: 0.4733521610032767
purpose: []
